// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumLink: typeof import('./src/components/common/AlbumLink.vue')['default'];
    ArtistsItem: typeof import('./src/components/item/ArtistsItem.vue')['default'];
    ArtistsLink: typeof import('./src/components/common/ArtistsLink.vue')['default'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSlider: typeof import('element-plus/es')['ElSlider'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    IconSvg: typeof import('./src/components/IconSvg.vue')['default'];
    MusicProgress: typeof import('./src/components/common/MusicProgress.vue')['default'];
    PlayButton: typeof import('./src/components/common/PlayButton.vue')['default'];
    PlayListItem: typeof import('./src/components/item/PlayListItem.vue')['default'];
    PlayListScroll: typeof import('./src/components/PlayListScroll.vue')['default'];
    PlayListTable: typeof import('./src/components/PlayListTable.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SearchInput: typeof import('./src/components/SearchInput.vue')['default'];
    SectionList: typeof import('./src/components/common/SectionList.vue')['default'];
    SongAvatar: typeof import('./src/components/common/SongAvatar.vue')['default'];
    SongImage: typeof import('./src/components/common/SongImage.vue')['default'];
    SongItem: typeof import('./src/components/item/SongItem.vue')['default'];
    TagItem: typeof import('./src/components/item/TagItem.vue')['default'];
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll'];
  }
}
