name: Update h5
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install 安装依赖
        run: npm install
      - name: npm run all 生成发布
        run: npm run all
        env:
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
          REMOTEDIR: ${{ secrets.REMOTEDIR }}
